packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - workerd
patchedDependencies:
  next-themes@0.4.6: patches/next-themes@0.4.6.patch
